"""Generates demos/gpt2/unicode.bend: the character classes of the GPT-2 pre-tokenizer regex
for non-ASCII code points, computed with the `regex` module (\\s, \\p{L}, \\p{N}).

A table entry is lo, hi, class (1 digit, 2 other, 3 whitespace) for the code points that are
NOT letters; every code point outside the table is a letter. CJK ideographs and Hangul are
letters and skipped, and code points above U+1FFFF are all treated as letters."""
import os, sys
import regex

LETTER_BLOCKS = [(0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xAC00, 0xD7A3)]
LIMIT = 0x1FFFF


def cls(cp):
    ch = chr(cp)
    if regex.match(r"\s", ch): return 3
    if regex.match(r"\p{L}", ch): return 0
    if regex.match(r"\p{N}", ch): return 1
    return 2


def table():
    out, cur = [], None
    cp = 128
    while cp <= LIMIT:
        skip = next((hi for lo, hi in LETTER_BLOCKS if lo <= cp <= hi), None)
        if skip is not None:
            if cur: out.append(cur); cur = None
            cp = skip + 1
            continue
        if 0xD800 <= cp <= 0xDFFF:
            c = 2
        else:
            c = cls(cp)
        if c == 0:
            if cur: out.append(cur); cur = None
        elif cur and cur[2] == c and cur[1] == cp - 1:
            cur[1] = cp
        else:
            if cur: out.append(cur)
            cur = [cp, cp, c]
        cp += 1
    if cur: out.append(cur)
    return out


def main():
    t = table()
    lines = []
    for i in range(0, len(t), 6):
        lines.append("  " + ", ".join(f"{lo}, {hi}, {c}" for lo, hi, c in t[i:i + 6]))
    body = ",\n".join(lines)
    src = f"""# GENERATED by reference/gen_unicode_table.py (regex {regex.__version__}); do not edit.
# Non-letter code points >= 128 as (lo, hi, class) triples, sorted:
# class 1 = digit (\\p{{N}}), 2 = other (not \\s, \\p{{L}}, \\p{{N}}), 3 = whitespace (\\s).
# Anything not listed (and every code point above U+1FFFF) is a letter. {len(t)} ranges.

import Base

def non_letters() -> List<&2, U32>:
  [
{body}
  ]
"""
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "demos/gpt2/unicode.bend")
    open(path, "w").write(src)
    print(len(t), "ranges ->", path)


main()
