"""Writes a Bend program with L dense layers whose sizes are all different, to measure how the
checker and the build scale with depth (an answer to "how bad do compile times get on deeper nets?").

Layer i maps Mat<n, d_i> to Mat<n, d_{i+1}> with d_i = 16 + i, so every layer has its own type and
the checker cannot reuse the work of another. The batch size n is a variable, as in a real model.

  python scripts/gen_deep_mlp.py L > /tmp/deep.bend
"""
import sys

L = int(sys.argv[1])
d = [16 + i for i in range(L + 1)]
out = [
    f"# {L} dense layers with distinct sizes (generated by scripts/gen_deep_mlp.py)",
    "import Base",
    "import bend-ml-tensor-array@0.1.3.0/main.bend as TA",
    "",
    "def take_c(-n: Nat, -k: Nat, -m: Nat, x: TA.MMul<n, k, m>) -> TA.Mat<n, m>:",
    "  match x:",
    "    case TA.MMul{a, w, c}:",
    "      c",
    "",
]
for i in range(L):
    a, b = d[i], d[i + 1]
    out += [
        f"def w{i}() -> TA.Mat<{a}n, {b}n>:",
        f"  TA.Mat.fill({a}n, {b}n, 0.01)",
        "",
        f"def layer{i}(+n: Nat, x: TA.Mat<n, {a}n>) -> TA.Mat<n, {b}n>:",
        f"  TA.Mat.relu(n, {b}n, take_c(n, {a}n, {b}n, TA.Mat.matmul(n, {a}n, {b}n, 0n, x, w{i}())))",
        "",
    ]
# forward_i applies layers i .. L-1; defined from the last one up, since a def must come before its use
out += [f"def forward{L}(+n: Nat, x: TA.Mat<n, {d[L]}n>) -> TA.Mat<n, {d[L]}n>:", "  x", ""]
for i in reversed(range(L)):
    out += [f"def forward{i}(+n: Nat, x: TA.Mat<n, {d[i]}n>) -> TA.Mat<n, {d[L]}n>:",
            f"  forward{i + 1}(n, layer{i}(n, x))", ""]
out += [
    "def size(+n: Nat, m: TA.Mat<n, " + f"{d[L]}n" + ">) -> Nat:",
    "  n",
    "",
    "def main() -> Nat:",
    f"  size(4n, forward0(4n, TA.Mat.fill(4n, {d[0]}n, 1.0)))",
]
print("\n".join(out))
